"""Add email column to Todo table

Revision ID: 105985e95d2d
Revises: 
Create Date: 2024-01-17 15:15:47.953672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105985e95d2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('deadline')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
